---
Name: collapsiblewidgets
After: "silverstripe/widgets#*"
---
SilverStripe\Widgets\Forms\WidgetAreaEditor:
    extensions:
        - 'WebbuildersGroup\CollapsibleWidgets\Extensions\CollapsibleWidgets'
